### ISSUE TITLE
Edimax authentication error on firmware >2.04

### ISSUE THREAD

**Issue by fabaff** [rkabadi/pyedimax#4]
https://github.com/home-assistant/home-assistant/issues/9119

**Comment by andreipop2005** [comment]
Any news about this?

**Comment by andreipop2005** [comment]
Problem is related to digest authentication header in request, I fixed it and opened a pull request.

**Comment by andreipop2005** [comment]
Please accept pull request https://github.com/rkabadi/pyedimax/pull/5, it works.

**Comment by PyJay** [comment]
I can confirm that @andreipop2005 fix works. Please accept the pull request.

**Comment by andreipop2005** [comment]
Solved by https://github.com/home-assistant/home-assistant/pull/12873

**Comment by bdurrer** [comment]
The problem persists with the current firmware v3.0+, as it now requires digest authentication.
A quick and easy non-backwards-compatible fix would be to switch over to `requests.get(url, auth=HTTPDigestAuth(user, pass))`

**Comment by andreipop2005** [comment]
> The problem persists with the current firmware v3.0+, as it now requires digest authentication.
> A quick and easy non-backwards-compatible fix would be to switch over to `requests.get(url, auth=HTTPDigestAuth(user, pass))`

I have no idea about this new firmware. I will check it out.

**Comment by bdurrer** [comment]
It just occurred to me that v3 firmware might only be available on the sp-2101w v2! I guess that's another argument for having an auth type option in HA.
I'll experiment with it next week

**Comment by bdurrer** [comment]
It just occurred to me that the v3 firmware might be only for the  sp-2101w V2 switch.

Maybe the auth type has to be configurable in HA. I will experiment with it next week

**Comment by bdurrer** [comment]
Sorry, I accidentally looked at the original code and did not realize that digest-auth is already in place. Sadly, the problem is much worse. Conclusion to a lot of googling: "it is a terribly broken device".

The sp-2101w **v2** ...
* is different from v1 and uses an other firmaware (v3.00c currently).
* the new app does not let you configure a password anymore, it is instead somehow generated under the hood. It's not clear how it is shared with the app.
* only a manual way for optaining the password is known.
* you cannot downgrade it (in contrast to the v1 devices) , as it will not switch anymore.


Manual password extraction:
1. reset the device
2. configure it with the EdiSmart app
3. do not reset or restart the device! It has a telnet service open from the configuration-mode.
4. connect with telnet on port 1355
5. `nvc all` should return some info, the password should appear is on the last line

**Comment by 5-c-o** [comment]
> 
> 
> Sorry, I accidentally looked at the original code and did not realize that digest-auth is already in place. Sadly, the problem is much worse. Conclusion to a lot of googling: "it is a terribly broken device".
> 
> The sp-2101w **v2** ...
> 
>     * is different from v1 and uses an other firmaware (v3.00c currently).
> 
>     * the new app does not let you configure a password anymore, it is instead somehow generated under the hood. It's not clear how it is shared with the app.
> 
>     * only a manual way for optaining the password is known.
> 
>     * you cannot downgrade it (in contrast to the v1 devices) , as it will not switch anymore.
> 
> 
> Manual password extraction:
> 
>     1. reset the device
> 
>     2. configure it with the EdiSmart app
> 
>     3. do not reset or restart the device! It has a telnet service open from the configuration-mode.
> 
>     4. connect with telnet on port 1355
> 
>     5. `nvc all` should return some info, the password should appear is on the last line

Port 1355 doesn't seem to be open on my sp-2101w on v3.00c. Port 10000/http is but that's it, I've scanned range 1-10000 both during setup mode (via wifi directly) and post-setup (before rebooting.) Any advice?

Edit: seems you need to log into the web interface first (via http://192.168.20.3:10000/tnb2 when directly connected during setup, creds are admin/1234 at this stage.) Post-setup telnet to new local IP:1355 as above. I connected before I entered the device name.
